apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  # This define which pods are going to be represented by this Service
  # This service becomes a network endpoint for either other services
  # or maybe external users to connecto (eg., Browser)
  selector:
    app: queue
  ports:
    - name: http
      port: 8161
      nodePort: 30010

  type: NodePort
